# Generated by Django 5.1.5 on 2026-03-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskp',
            name='is_permanent_reschedule',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
