# Generated by Django 5.1.5 on 2026-04-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0002_alter_taskp_is_permanent_reschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='chemical_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
