# Generated by Django 5.1.4 on 2025-01-15 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0002_equipment_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='equipment',
        ),
    ]
