# Generated by Django 5.1.4 on 2025-01-21 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0003_remove_task_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskp',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works4cdp.equipment'),
        ),
    ]
