# Generated by Django 5.2.10 on 2026-05-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0003_alter_assay_chemical_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
