# Generated by Django 5.1.5 on 2025-01-22 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0004_taskp_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskp',
            name='equipment',
        ),
        migrations.AddField(
            model_name='task',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works4cdp.equipment'),
        ),
    ]
