# Generated by Django 5.2.10 on 2026-05-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0004_assay_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assay',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddConstraint(
            model_name='assay',
            constraint=models.UniqueConstraint(fields=('id', 'timestamp'), name='works4cdp_assay_pkey'),
        ),
    ]
