# Generated by Django 5.1.5 on 2025-02-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0005_remove_taskp_equipment_task_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskp',
            name='turn',
        ),
        migrations.AddField(
            model_name='task',
            name='turn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
