# Generated by Django 5.1.5 on 2025-02-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0006_remove_taskp_turn_task_turn'),
    ]

    operations = [
        migrations.CreateModel(
            name='VTaskP',
            fields=[
                ('planta', models.CharField(max_length=255)),
                ('sistema', models.CharField(max_length=255)),
                ('equipo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('tarea_descripcion', models.TextField()),
                ('tag', models.CharField(max_length=100)),
                ('id_task', models.IntegerField()),
                ('semana', models.IntegerField()),
                ('fecha', models.DateField()),
                ('dia_semana', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=50)),
                ('turno', models.CharField(max_length=10)),
                ('id_taskp', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'vtaskp',
                'managed': False,
            },
        ),
    ]
