# Generated by Django 5.1.5 on 2025-03-02 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0007_vtaskp'),
    ]

    operations = [
    ]
