# Generated by Django 5.1.5 on 2025-03-02 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0008_auto_20250302_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('day', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('state', models.CharField(max_length=10)),
                ('turn', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works4cdp.user')),
            ],
        ),
    ]
