# Generated by Django 5.1.5 on 2025-03-02 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0009_userp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskp',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='works4cdp.userp'),
        ),
    ]
