# Generated by Django 5.1.5 on 2025-03-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0010_alter_taskp_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='week',
            field=models.IntegerField(default=3231),
            preserve_default=False,
        ),
    ]
