# Generated by Django 5.2.10 on 2026-06-22 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0010_add_deshabilitado_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskp',
            name='corrective_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskp_instances', to='works4cdp.correctivetask'),
        ),
    ]
