# Generated by Django 5.1.5 on 2025-03-03 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0011_userp_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctivetask',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correctivetask',
            name='day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='correctivetask',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='works4cdp.userp'),
        ),
        migrations.AddField(
            model_name='correctivetask',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correctivetask',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskp',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
