# Generated by Django 5.2.10 on 2026-06-29 03:58

from django.db import migrations

def migrate_names_to_catalog(apps, schema_editor):
    Task = apps.get_model('works4cdp', 'Task')
    CorrectiveTask = apps.get_model('works4cdp', 'CorrectiveTask')
    TaskCatalog = apps.get_model('works4cdp', 'TaskCatalog')

    def clean_name(raw_name):
        if not raw_name:
            return None
        # Limpiar espacios adicionales al inicio y al final
        return raw_name.strip()

    # 1. Migrar nombres de plantillas de tareas preventivas (Task)
    for task in Task.objects.all():
        cleaned = clean_name(task.name)
        if not cleaned:
            continue
        
        # Obtener o crear la entrada en el catálogo para evitar duplicados exactos
        catalog_entry, _ = TaskCatalog.objects.get_or_create(
            name=cleaned,
            defaults={'description': task.description or ''}
        )
        task.task_catalog = catalog_entry
        task.save()

    # 2. Migrar nombres de tareas correctivas (CorrectiveTask) - Enfoque híbrido
    for c_task in CorrectiveTask.objects.all():
        cleaned = clean_name(c_task.name)
        if not cleaned:
            continue
        
        # Obtener o crear la entrada en el catálogo
        catalog_entry, _ = TaskCatalog.objects.get_or_create(
            name=cleaned,
            defaults={'description': c_task.description or ''}
        )
        c_task.task_catalog = catalog_entry
        c_task.save()

def reverse_migration(apps, schema_editor):
    Task = apps.get_model('works4cdp', 'Task')
    CorrectiveTask = apps.get_model('works4cdp', 'CorrectiveTask')
    
    # En caso de rollback, restaurar la información textual
    for task in Task.objects.all():
        if task.task_catalog and not task.name:
            task.name = task.task_catalog.name
            task.save()
            
    for c_task in CorrectiveTask.objects.all():
        if c_task.task_catalog and not c_task.name:
            c_task.name = c_task.task_catalog.name
            c_task.save()

class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0012_taskcatalog_alter_task_name_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_names_to_catalog, reverse_code=reverse_migration),
    ]
