# Generated by Django 5.1.5 on 2025-03-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0012_correctivetask_date_correctivetask_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctivetask',
            name='turn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
