# Generated by Django 5.2.10 on 2026-06-29 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0013_migrate_task_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works4cdp.taskcatalog'),
        ),
    ]
