# Generated by Django 5.1.5 on 2025-09-28 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0013_correctivetask_turn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='works4cdp.equipment')),
            ],
            options={
                'db_table': 'samples',
            },
        ),
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('instance', models.IntegerField(blank=True, null=True)),
                ('NFe', models.IntegerField(blank=True, null=True)),
                ('NCu', models.IntegerField(blank=True, null=True)),
                ('NZn', models.IntegerField(blank=True, null=True)),
                ('NMo', models.IntegerField(blank=True, null=True)),
                ('NKpSC', models.IntegerField(blank=True, null=True)),
                ('Nins', models.IntegerField(blank=True, null=True)),
                ('pFe', models.FloatField(blank=True, null=True)),
                ('pCu', models.FloatField(blank=True, null=True)),
                ('pZn', models.FloatField(blank=True, null=True)),
                ('pMo', models.FloatField(blank=True, null=True)),
                ('pIns', models.FloatField(blank=True, null=True)),
                ('pSol', models.FloatField(blank=True, null=True)),
                ('tara', models.FloatField(blank=True, null=True)),
                ('tweight', models.FloatField(blank=True, null=True)),
                ('dweight', models.FloatField(blank=True, null=True)),
                ('pweight', models.FloatField(blank=True, null=True)),
                ('chemical_id', models.IntegerField(blank=True, null=True)),
                ('ACu', models.FloatField(blank=True, null=True)),
                ('AZn', models.FloatField(blank=True, null=True)),
                ('AMo', models.FloatField(blank=True, null=True)),
                ('ASol', models.FloatField(blank=True, null=True)),
                ('Alns', models.FloatField(blank=True, null=True)),
                ('meta_user', models.CharField(blank=True, max_length=50, null=True)),
                ('turn', models.CharField(blank=True, max_length=10, null=True)),
                ('meta', models.ForeignKey(blank=True, db_column='meta_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assays', to='works4cdp.user')),
                ('sample', models.ForeignKey(blank=True, db_column='samples_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assays', to='works4cdp.sample')),
            ],
            options={
                'db_table': 'assays',
            },
        ),
    ]
