# Generated by Django 5.1.5 on 2025-09-28 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0014_sample_assay'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assay',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sample',
            table=None,
        ),
    ]
