# Generated by Django 5.2.10 on 2026-09-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0014_remove_task_name_alter_task_task_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='pOx',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
