# Generated by Django 5.1.5 on 2025-10-02 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0015_alter_assay_table_alter_sample_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assay',
            old_name='ACu',
            new_name='a1fe',
        ),
        migrations.RenameField(
            model_name='assay',
            old_name='AMo',
            new_name='a2cu',
        ),
        migrations.RenameField(
            model_name='assay',
            old_name='ASol',
            new_name='a3zn',
        ),
        migrations.RenameField(
            model_name='assay',
            old_name='AZn',
            new_name='a4mo',
        ),
        migrations.RenameField(
            model_name='assay',
            old_name='Alns',
            new_name='a5a5',
        ),
        migrations.RenameField(
            model_name='assay',
            old_name='NCu',
            new_name='n1fe',
        ),
        migrations.RenameField(
            model_name='assay',
            old_name='NFe',
            new_name='n2cu',
        ),
        migrations.RenameField(
            model_name='assay',
            old_name='NKpSC',
            new_name='n3zn',
        ),
        migrations.RenameField(
            model_name='assay',
            old_name='NMo',
            new_name='n4mo',
        ),
        migrations.RenameField(
            model_name='assay',
            old_name='NZn',
            new_name='n5ech5',
        ),
        migrations.RenameField(
            model_name='assay',
            old_name='Nins',
            new_name='n6sc',
        ),
        migrations.RemoveField(
            model_name='assay',
            name='meta',
        ),
        migrations.AddField(
            model_name='assay',
            name='a6sol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assay',
            name='a7a7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assay',
            name='n7ech7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assay',
            name='userp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works4cdp.userp'),
        ),
        migrations.AlterField(
            model_name='assay',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works4cdp.sample'),
        ),
    ]
