# Generated by Django 5.1.5 on 2025-10-02 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0016_rename_acu_assay_a1fe_rename_amo_assay_a2cu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assay',
            old_name='userp_id',
            new_name='userp',
        ),
    ]
