# Generated by Django 5.1.5 on 2025-12-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0017_rename_userp_id_assay_userp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='sn',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
