# Generated by Django 5.1.5 on 2026-02-16 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0018_sample_sn'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssaysPsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('instance', models.IntegerField(blank=True, null=True)),
                ('tara', models.FloatField(blank=True, null=True)),
                ('tweight', models.FloatField(blank=True, null=True)),
                ('dweight', models.FloatField(blank=True, null=True)),
                ('psolid', models.FloatField(blank=True, null=True)),
                ('pW48', models.FloatField(blank=True, null=True)),
                ('pW65', models.FloatField(blank=True, null=True)),
                ('pW100', models.FloatField(blank=True, null=True)),
                ('pW150', models.FloatField(blank=True, null=True)),
                ('pW200', models.FloatField(blank=True, null=True)),
                ('pW325', models.FloatField(blank=True, null=True)),
                ('pW400', models.FloatField(blank=True, null=True)),
                ('aAvg', models.FloatField(blank=True, null=True)),
                ('aSD', models.FloatField(blank=True, null=True)),
                ('aDensity', models.FloatField(blank=True, null=True)),
                ('aSol', models.FloatField(blank=True, null=True)),
                ('aP48', models.FloatField(blank=True, null=True)),
                ('aP65', models.FloatField(blank=True, null=True)),
                ('aP100', models.FloatField(blank=True, null=True)),
                ('aP150', models.FloatField(blank=True, null=True)),
                ('aP200', models.FloatField(blank=True, null=True)),
                ('aP325', models.FloatField(blank=True, null=True)),
                ('aP400', models.FloatField(blank=True, null=True)),
                ('P80', models.FloatField(blank=True, null=True)),
                ('P50', models.FloatField(blank=True, null=True)),
                ('pP48', models.FloatField(blank=True, null=True)),
                ('pP65', models.FloatField(blank=True, null=True)),
                ('pP100', models.FloatField(blank=True, null=True)),
                ('pP150', models.FloatField(blank=True, null=True)),
                ('pP200', models.FloatField(blank=True, null=True)),
                ('pP325', models.FloatField(blank=True, null=True)),
                ('pP400', models.FloatField(blank=True, null=True)),
                ('an_50_um', models.FloatField(blank=True, null=True)),
                ('a50_100_um', models.FloatField(blank=True, null=True)),
                ('a100_150_um', models.FloatField(blank=True, null=True)),
                ('a150_200_um', models.FloatField(blank=True, null=True)),
                ('a200_250_um', models.FloatField(blank=True, null=True)),
                ('a250_300_um', models.FloatField(blank=True, null=True)),
                ('a300_350_um', models.FloatField(blank=True, null=True)),
                ('a350_400_um', models.FloatField(blank=True, null=True)),
                ('a400_450_um', models.FloatField(blank=True, null=True)),
                ('a450_500_um', models.FloatField(blank=True, null=True)),
                ('a500_550_um', models.FloatField(blank=True, null=True)),
                ('a550_600_um', models.FloatField(blank=True, null=True)),
                ('a600_650_um', models.FloatField(blank=True, null=True)),
                ('a650_700_um', models.FloatField(blank=True, null=True)),
                ('a700_750_um', models.FloatField(blank=True, null=True)),
                ('a750_800_um', models.FloatField(blank=True, null=True)),
                ('a800_850_um', models.FloatField(blank=True, null=True)),
                ('a850_900_um', models.FloatField(blank=True, null=True)),
                ('a900_950_um', models.FloatField(blank=True, null=True)),
                ('a950_1000_um', models.FloatField(blank=True, null=True)),
                ('a1000_n_um', models.FloatField(blank=True, null=True)),
                ('meta_user', models.CharField(blank=True, max_length=50, null=True)),
                ('turn', models.CharField(blank=True, max_length=10, null=True)),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works4cdp.sample')),
                ('userp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works4cdp.userp')),
            ],
        ),
    ]
