# Generated by Django 5.2.10 on 2026-03-07 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0019_assayspsi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assay',
            name='turn',
        ),
    ]
