# Generated by Django 5.2.10 on 2026-03-07 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0020_remove_assay_turn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='assay',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='assayspsi',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='correctivetask',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='taskp',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='userp',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='vtaskp',
            options={'managed': False, 'ordering': ['-id_taskp']},
        ),
    ]
