# Generated by Django 5.1.5 on 2026-03-07 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0021_alter_area_options_alter_assay_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works4cdp.user'),
        ),
    ]
