# Generated by Django 5.1.5 on 2026-03-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0022_alter_userp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userp',
            name='state',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
