# Generated by Django 5.1.5 on 2026-03-12 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0023_alter_userp_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userp',
            options={},
        ),
        migrations.RenameField(
            model_name='userp',
            old_name='day',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='assay',
            name='userp',
        ),
        migrations.RemoveField(
            model_name='assayspsi',
            name='userp',
        ),
        migrations.RemoveField(
            model_name='correctivetask',
            name='turn',
        ),
        migrations.RemoveField(
            model_name='correctivetask',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='taskp',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='userp',
            name='date',
        ),
        migrations.RemoveField(
            model_name='userp',
            name='state',
        ),
        migrations.RemoveField(
            model_name='userp',
            name='turn',
        ),
        migrations.RemoveField(
            model_name='userp',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userp',
            name='week',
        ),
        migrations.RemoveField(
            model_name='userp',
            name='year',
        ),
        migrations.AddField(
            model_name='assay',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works4cdp.user'),
        ),
        migrations.AddField(
            model_name='assayspsi',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works4cdp.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works4cdp.userp'),
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('day', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('turn', models.CharField(blank=True, max_length=10, null=True)),
                ('overtime', models.IntegerField(default=0)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works4cdp.userp')),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Exception_calendar', to='works4cdp.user')),
            ],
            options={
                'ordering': ['-date', 'group'],
            },
        ),
        migrations.CreateModel(
            name='TaskGroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works4cdp.calendar')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works4cdp.task')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
