# Generated by Django 5.1.5 on 2026-03-12 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0024_alter_userp_options_rename_day_userp_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='user',
            field=models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Exception_calendar', to='works4cdp.user'),
        ),
    ]
