# Generated by Django 5.2.10 on 2026-03-13 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0025_alter_calendar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskgroupassignment',
            name='task',
        ),
        migrations.AddField(
            model_name='taskgroupassignment',
            name='taskp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='works4cdp.taskp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskp',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskp',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskp',
            name='is_permanent_reschedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskp',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='works4cdp.estado'),
        ),
        migrations.AlterField(
            model_name='taskp',
            name='priority',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
