# Generated by Django 5.1.5 on 2026-03-13 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0026_remove_taskgroupassignment_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskp',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='works4cdp.userp'),
        ),
    ]
