# Generated by Django 5.1.5 on 2026-03-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0027_taskp_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='turn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
