# Generated by Django 5.1.5 on 2026-03-13 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0028_assay_turn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assay',
            options={},
        ),
        migrations.RemoveField(
            model_name='assay',
            name='user',
        ),
        migrations.AddField(
            model_name='assay',
            name='userp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works4cdp.userp'),
        ),
    ]
