# Generated by Django 5.1.5 on 2026-03-13 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works4cdp', '0029_alter_assay_options_remove_assay_user_assay_userp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assay',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='assay',
            name='turn',
        ),
        migrations.RemoveField(
            model_name='assay',
            name='userp',
        ),
        migrations.AddField(
            model_name='assay',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works4cdp.user'),
        ),
    ]
